const UserTypes = {
  SIGN_iN_START: "SIGN_iN_START",
  SIGN_iN_SUCCESS: "SIGN_iN_SUCCESS",
  SIGN_iN_FAILURE: "SIGN_iN_FAILURE",
  CHECK_IS_USER_LOGGED_IN: "CHECK_IS_USER_LOGGED_IN"
};

export default UserTypes;
