const UserTypes = {
  SIGN_iN_START: "SIGN_iN_START",
  SIGN_iN_SUCCESS: "SIGN_iN_SUCCESS",
  SIGN_iN_FAILURE: "SIGN_iN_FAILURE",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
  CHECK_IS_USER_LOGGED_IN: "CHECK_IS_USER_LOGGED_IN",
  USER_IS_LOGGED_IN: "USER_IS_LOGGED_IN",
  USER_IS_NOT_LOGGED_IN: "USER_IS_NOT_LOGGED_IN"
};

export default UserTypes;
